name: GitHub Metrics

on:
  schedule: [{cron: "0 */12 * * *"}]   # Runs every 12 hours
  workflow_dispatch:                    # Allow manual trigger

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          # Your Classic PAT stored in GitHub Secrets
          token: ${{ secrets.METRICS_TOKEN }}

          # Your GitHub username
          user: Nsanjayboruds

          # Template style
          template: classic

          # Base sections
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata

          # Plugins
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 2%
          plugin_languages_indepth: yes

          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: classic

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_followup: yes
          plugin_followup_sections: repositories, user
